- name: Restart containerd
  systemd:
    name: containerd
    state: restarted
    enabled: yes
    
- name: Initialize the Kubernetes cluster using kubeadm
  command: kubeadm init --kubernetes-version={{ kubernetes_version }}

- name: Créer le répertoire .kube
  file:
        path: "/home/{{ ansible_user }}/.kube"
        state: directory
        mode: '0755'

- name: Copier le fichier admin.conf vers .kube/config
  copy:
        src: /etc/kubernetes/admin.conf
        dest: "/home/{{ ansible_user }}/.kube/config"
        mode: '0644'

- name: Changer le propriétaire du fichier config
  file:
        path: "/home/{{ ansible_user }}/.kube/config"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'

- name: Install flannel pod network
  become: false
  command: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/calico.yaml

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  become: false
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
  
- name: Ajouter l'auto-complétion kubectl au fichier .bashrc
  shell: |
    echo 'source <(kubectl completion bash)' >> /home/{{ ansible_user }}/.bashrc
  args:
    executable: /bin/bash

- name: Sourcer le fichier bashrc
  shell: source /home/{{ ansible_user }}/.bashrc
  args:
    executable: /bin/bash